const { withProjectBuildGradle } = require('expo/config-plugins');

// The app only uses Agora RTC for doctor audio/video consultations - it
// never uses Agora's screen sharing feature. But the Agora RTC SDK ships a
// screen-sharing extension module by default, which pulls in the
// FOREGROUND_SERVICE_MEDIA_PROJECTION permission. Google Play then requires
// a "Foreground service permissions" declaration (with a demo video) for
// that permission on every release unless it's excluded. See
// react-native-agora's own README, "FOREGROUND_SERVICE_MEDIA_PROJECTION
// permission" section, which documents this exact exclusion.
//
// This has to live in a config plugin (not a manual edit to
// android/build.gradle) because android/ is gitignored and regenerated by
// `expo prebuild` - a manual edit would silently disappear on the next
// clean prebuild (another machine, CI, EAS Build).
const EXCLUDE_SNIPPET = `
    configurations.configureEach {
        exclude group: "io.agora.rtc", module: "full-screen-sharing"
    }`;

module.exports = function withAgoraScreenShareExclusion(config) {
    return withProjectBuildGradle(config, (config) => {
        if (config.modResults.language !== 'groovy') {
            throw new Error('withAgoraScreenShareExclusion only supports Groovy project build.gradle');
        }
        if (!config.modResults.contents.includes('full-screen-sharing')) {
            config.modResults.contents = config.modResults.contents.replace(
                /allprojects\s*{/,
                (match) => `${match}\n${EXCLUDE_SNIPPET}`
            );
        }
        return config;
    });
};
